name: Market Scanner

on:
  schedule:
    # Run every 5 minutes during market hours (IST: 9:15 AM - 3:30 PM)
    - cron: '*/5 3:45-10:00 * * 1-5'
  workflow_dispatch:  # Manual trigger

jobs:
  scan-market:
    runs-on: ubuntu-latest
    
    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run market scanner
      run: python volume_detector.py